slide to frontpage
lipefsa/house_of_barber pull request #3
Opened 2023-08-14 03:51 UTC by lipefsa

slider adicionado
cta corrigido
banner ajustado

2023-08-14 21:42 UTC, JoaoCFN commented on .gitignore
> +.todo
@lipefsa Recomendo remover esse arquivo .todo do gitignore. Ele na verdade não deveria subir com essa PR.

2023-08-14 21:44 UTC, JoaoCFN commented on pages/landing_page/landing_page.js
> +
@lipefsa Recomendo remover os espaços vazios remanescentes nesse arquivo. Ficou muito espaço fantasma.

2023-08-14 21:45 UTC, JoaoCFN commented on pages/landing_page/content/landing_page_content.php
> +<div class="swiper mySwiper">
@lipefsa Ajustar formatação do código nesse trecho

2023-08-14 21:47 UTC, JoaoCFN commented on pages/landing_page/landing_page.js
> +                            <div class='card area-cliente-card'>
@lipefsa Recomendo trocar a nomenclatura aqui. `area-cliente-card` não faz sentido nesse contexto. Busca colocar um nome que faça sentido para a landing page.

2023-08-14 21:47 UTC, JoaoCFN commented on pages/landing_page/landing_page.css
> +.area-cliente .card-title {
@lipefsa Mesmo ponto sobre a nomenclatura aqui. `area-cliente` não é um bom nome para uma seção dentro da landing page.

2023-08-14 21:50 UTC, JoaoCFN commented on assets/images/login.png
@lipefsa Vê se tu consegue achar uma imagem mais próxima da tela de login atual para a substituição. Não vejo essas imagens conversando muito com a identidade visual do sistema, sabe?

2023-08-14 21:51 UTC, JoaoCFN commented on assets/images/login2.png
@lipefsa Mesmo ponto sobre as imagens aqui.

2023-08-14 21:51 UTC, JoaoCFN requested changes
@lipefsa 
Descrevi alguns ajustes que devem ser feitos na PR nos comentários

2023-08-15 01:23 UTC, lipefsa commented
corrigido

2023-08-15 03:37 UTC, merged